### PR TITLE
Main responsive

### PR DESCRIPTION
**Pull request by onedebos**
## In this Commit

- Made the main content of the page responsive and reset the height of the page to take up the entire viewport.

### CODE REVIEW

**Comment by onedebos** [comment]
@davidauza-engineer @hugopassos @evaveskova I fixed the responsiveness issue, guys. Please take a look.

**Comment by onedebos** [comment]
When I try this out on a smaller screen in my Firefox and chrome browser, I don't notice the issue. 
Screen Shot 2020-03-18 at 09 36 42

**Comment by davidauza-engineer** [comment]
Great job @onedebos!

@evaveskova will work on improving the last issue on iPhone SE and some minor improvements before merging. @evaveskova you can continue adding commits on this branch.

Thank you guys

**Review by davidauza-engineer — COMMENTED** [review]
I think we should be closing this XD

**Pull request closed without merging**
